### ISSUE TITLE
Unclear how to access the insight api

### ISSUE THREAD

**Issue by HasseM** [jeshan/bitcore-testnet#3]
I'm rather new to docker, so I am risking to ask something obvious but I am totally lost. I am running the docker container and it syncs to the blockchain okay. But how can I access the insight API from outside the docker container? I basically tried http://localhost:everypossibleport wihtout luck.  I think it must be something obvous that I am missing. Any tips would be greatly appreciated!

**Comment by jeshan** [comment]
A port will be assigned for you by default. I explained all this in a previous comment:
https://github.com/jeshan/bitcore-node/issues/1#issuecomment-702891525

Let me know.

**Comment by HasseM** [comment]
Thanks. I tried using: 
docker run --rm -P -v /root/bitcoin-node --name testnet jeshan/bitcore-node
To run the image and open localhost:49153 in the browser but I keep getting ERR_EMPTY_RESPONSE (any other port number gets me a ERR_CONNECTION_REFUSED). I'n running docker in Win 10 with WSL2. But that should not make a difference I think.

Am I right that I should see a webpage, even if it is still syncing the blockchain? Starting web, Insight UI & API messages were without error. So I am expecting that the webserver should be up and running pretty fast after starting the container.

**Comment by jeshan** [comment]
did you open the urls as shown in my screenshots there? it shows that both insight and api are working.

**Comment by HasseM** [comment]
Yes,
http://localhost:49153/insight
and
http://localhost:49153/insight-api/tx/send

![image](https://user-images.githubusercontent.com/7515641/115579400-6d8b4480-a2c6-11eb-9964-22fd2ed2fc70.png)

error message is "this page does not work, localhost did not send data"

also no strange things here:
![image](https://user-images.githubusercontent.com/7515641/115579773-c65add00-a2c6-11eb-8bf8-4afcc7eddd08.png)

**Comment by jeshan** [comment]
There are different ports at play here. Look closely at the example `docker run` just gave me:

```
9cee5f5154e9        jeshan/bitcore-node   "/usr/bin/dumb-init …"   9 seconds ago       Up 6 seconds (health: starting)   0.0.0.0:32772->3001/tcp, 0.0.0.0:32771->3232/tcp, 0.0.0.0:32770->6667/tcp, 0.0.0.0:32769->8333/tcp, 0.0.0.0:32768->18333/tcp   testnet
```

The one that is mapped to **port 3001** (here 32772 on the host) is the correct one to access the insight UI:
![image](https://user-images.githubusercontent.com/1020565/115581745-59047780-a2d9-11eb-9dd9-28a50340ed02.png)

This same port exposes the api:
![image](https://user-images.githubusercontent.com/1020565/115582068-a1239a00-a2d9-11eb-8d6f-ee1b79bb2152.png)

I'll let you find out what the other ports are for. You'll have to manage now. I haven't worked on bitcore for years and can hardly remember these details.

**Comment by HasseM** [comment]
YES! It was 49157. Could see that one mapped to 3001.
Thanks a lot!

![image](https://user-images.githubusercontent.com/7515641/115584503-1cca1a80-a2cb-11eb-9c18-594cb1ce4034.png)
