### ISSUE TITLE
livenet not working?

### ISSUE THREAD

**Issue by HasseM** [jeshan/bitcore-testnet#4]
Sorry for bothering you but when I try:
docker run --env NETWORK=livenet --rm -P -v /root/bitcoin-node --name livenet jeshan/bitcore-node

It still is:
info: Using network: testnet

So, how to get it to use the livenet?

Anyhow, your readme can be improved (also the example names the livenetwork as testnet).

**Comment by jeshan** [comment]
it should have been `BITCOIN_NETWORK` (it was in the Dockerfile). I have updated the readme.

**Comment by HasseM** [comment]
Great. Seems to work now (letting it sync for some time now).
