### ISSUE TITLE
Cannot turn off rate limiter

### ISSUE THREAD

**Issue by HasseM** [jeshan/bitcore-testnet#5]
I run in a too many requets problem. So I tried to turn of the ratelimiter by adding this in bitcore-node.json:

"servicesConfig": {
"insight-api": {
"disableRateLimiter": true
}
}

But then the container wont run at all anymore....

So, is there an easy way to turn off this ratelimit problem of the insight-api?

**Comment by jeshan** [comment]
> then the container wont run at all

What does the error say?

> is there an easy way to turn off this ratelimit problem

You should be doing whatever is documented by the bitcore project (and not this one). My project is only about providing a docker file.
Make sure to check the docs for the insight api version in the docker container.

**Comment by HasseM** [comment]
I didnt copy the exact error, but it was something about an error in the config file that I edited. So obviously the solution that I found was wrong despite the advice that I found elsewhere. Problem with the docker was that it directly shut down because  of this error. So I am now waiting for the network to be synced again.... can try again in a couple of hours.

Would it be better to use a volume or so for the network sync data?

Anyhow, I would appreciate any advice on turning of the rate limiter. I consider it a main reason for running it locally in a docker.

**Comment by jeshan** [comment]
> Problem with the docker was that it directly shut down

Yes but the container is probably still here and you can find its logs. I suggest you familiarise yourself with docker as it will become relevant for you in the future.

> So I am now waiting for the network to be synced again

Consider testing it in the cloud where you can get higher speed!

> I would appreciate any advice on turning of the rate limiter.

No, I will help if possible as long as it's directly relevant to this repository (I'm busy).
